[error] com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Access denied for user 'admin'@'localhost' (using password: YES)
[error] 	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
[error] 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
[error] 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[error] 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[error] 	at com.knoldus.bootstrap.DataBaseInstantiator.<init>(DataBaseInstantiator.scala:25)
[error] 	at com.knoldus.bootstrap.Application$.delayedEndpoint$com$knoldus$bootstrap$Application$1(Application.scala:11)
[error] 	at com.knoldus.bootstrap.Application$delayedInit$body.apply(Application.scala:7)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1(App.scala:76)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at com.knoldus.bootstrap.Application$.main(Application.scala:7)
[error] 	at com.knoldus.bootstrap.Application.main(Application.scala)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[error] 	at sbt.Run.invokeMain(Run.scala:143)
[error] 	at sbt.Run.execute$1(Run.scala:93)
[error] 	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
[error] 	at sbt.Run$.executeSuccess(Run.scala:186)
[error] 	at sbt.Run.runWithLoader(Run.scala:120)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)
[error] 	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[error] Caused by: java.sql.SQLException: Access denied for user 'admin'@'localhost' (using password: YES)
[error] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[error] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[error] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[error] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
[error] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[error] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[error] 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[error] 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
[error] 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[error] 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
[error] 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
[error] 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[error] 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[error] 	at com.knoldus.bootstrap.DataBaseInstantiator.<init>(DataBaseInstantiator.scala:25)
[error] 	at com.knoldus.bootstrap.Application$.delayedEndpoint$com$knoldus$bootstrap$Application$1(Application.scala:11)
[error] 	at com.knoldus.bootstrap.Application$delayedInit$body.apply(Application.scala:7)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1(App.scala:76)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at com.knoldus.bootstrap.Application$.main(Application.scala:7)
[error] 	at com.knoldus.bootstrap.Application.main(Application.scala)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[error] 	at sbt.Run.invokeMain(Run.scala:143)
[error] 	at sbt.Run.execute$1(Run.scala:93)
[error] 	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
[error] 	at sbt.Run$.executeSuccess(Run.scala:186)
[error] 	at sbt.Run.runWithLoader(Run.scala:120)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)
[error] 	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[error] (Compile / run) com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Access denied for user 'admin'@'localhost' (using password: YES)
